image: chocobozzz/peertube-ci:14

stages:
  - clients
  - docker-nightly

cache:
  key: yarn
  paths:
    - .yarn-cache
    - cached-fixtures

# build-openapi-clients:
#   stage: clients
#   only:
#     refs:
#       - master
#       - schedules
#     changes:
#       - support/doc/api/openapi.yaml
#   script:
#     - apt-get update -qq
#     - apt-get -yqqq install openjdk-8-jre
#     - yarn install --pure-lockfile
#     - scripts/openapi-peertube-version.sh
#     - scripts/openapi-clients.sh

build-nightly:
  stage: docker-nightly
  only:
    - schedules
  script:
    - yarn install --pure-lockfile --cache-folder .yarn-cache
    - npm run nightly
    - mkdir "${HOME}/.ssh"
    - chmod 700 "${HOME}/.ssh"
    - if [ ! -z ${DEPLOYEMENT_KNOWN_HOSTS+x} ]; then echo -e "${DEPLOYEMENT_KNOWN_HOSTS}" > ${HOME}/.ssh/known_hosts; fi
    - eval `ssh-agent -s`
    - if [ ! -z ${DEPLOYEMENT_KEY+x} ]; then ssh-add <(echo "${DEPLOYEMENT_KEY}"); fi
    - if [ ! -z ${DEPLOYEMENT_KEY+x} ]; then scp ./peertube-nightly-* ${DEPLOYEMENT_USER}@${DEPLOYEMENT_HOST}:../../web/nightly; fi
